---
abstract: 'Text::Hogan - A mustache templating engine statement-for-statement cloned from hogan.js'
author:
  - 'Alex Balhatchet'
build_requires:
  Data::Visitor::Callback: '0.30'
  Path::Tiny: '0.059'
  Test::More: '1.001008'
  Try::Tiny: '0.22'
  YAML: '1.13'
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Hogan
requires:
  Clone: '0.37'
  Ref::Util: '0.204'
  Scalar::Util: '1.41'
  Text::Trim: '1.02'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/kaoru/Text-Hogan/issues
  repository: git://github.com/kaoru/Text-Hogan
version: '2.03'
x_serialization_backend: 'YAML::Tiny version 1.69'
